### ISSUE TITLE
Wrong file

### ISSUE THREAD

**Issue by petestarkey** [du-otl/AS3-WebVTT#4]
Thank you for making this Joseph - much better than the standard component.

Looks to me like the AS3 demo isn't working because AS3-WebVTT/AS3demo/src/edu/du/captions/data/CaptionsParser.as is the wrong file? Captions load but don't render successfully.

Replacing it with AS3-WebVTT/edu/du/captions/data/CaptionsParser.as seems to sort the problem.

**Comment by josephlabrecque** [comment]
AH - thank you for the notice - I will give it a look!
